"""
Who Said It Part 3 & 4
San Kwon IB CS HL Y1

This is an extension of parts 1 and 2.
This algorithm determines whether a given text is more likely to be
written by William Shakespeare or by Jane Austen.

Resources:
https://www.pythonforbeginners.com/dictionary/how-to-use-dictionaries-in-python
"""

import math

# This is a function that calculates a score that measures
# the relevance of a word in a dictionary.
# The higher the score, the more relevance there is.
def get_score(word, counts):
    denominator = float(1 + counts["_total"])
    if word in counts:
        return math.log((1 + counts[word]) / denominator)
    else:
        return math.log(1 / denominator)

# This function returns the same given word but with
# no capitals and no extra non-letters
def normalize(word):
    return "".join(letter for letter in word if letter.isalpha()).lower()

# This function returns a dictionary with each of the words in a given text
# along with the number of times the word appeared in the text
def get_counts(filename):
    text = open(filename)
    result_dict = {}
    word_count = 0
    for line in text:
        words = line.split()
        for word in words:
            word = normalize(word)
            if word != "":
                if word in result_dict:
                    result_dict[word] = result_dict[word] + 1
                else:
                    result_dict[word] = 1
                word_count = word_count + 1
    result_dict["_total"] = word_count
    text.close()
    return result_dict

# This function uses the get_score function and the dictionaries
# generated by the get_counts function to predict if a given text
# is written by Shakespeare or Jane Austen
def predict(text, shakespeare_counts, austen_counts):
    shakespeare_score = 0
    austen_score = 0
    text = text.split()
    for word in text:
        word = normalize(word)
        if word != "":
            shakespeare_score = shakespeare_score + get_score(word, shakespeare_counts)
            austen_score = austen_score + get_score(word, austen_counts)
    if shakespeare_score > austen_score:
        print("I think that was written by William Shakespeare.")
    else:
        print("I think that was written by Jane Austen.")

shakespeare_counts = get_counts("hamlet.txt")
austen_counts = get_counts("pride-and-prejudice.txt")

# This asks the user for a text input and prints
# whether it is more likely to be written by Shakespeare or Jane Austen
text = input("Enter text: ")
predict(text, shakespeare_counts, austen_counts)



    

